# This file configure a GitHub workflow responsible to perform
# various checks related to the codebase.
#
# For that reason it's runned on every pull request and push to main.
#
# It does the following:
#  - Check lint passes (no eslint error on files)
#  - Check tests passes (none is failing)
#  - Upload code coverage from tests to codecov
#
# If all these steps are passing the workflow ends up
# publishing package on npm if needed. It will publish the npm package
# using the token found in secrets.NPM_TOKEN. Be sure to create this
# token in the GitHub repository.
#
# If you want to update this file it's recommended to use
# a YAML validator such as https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
# configured to validate this file with https://json.schemastore.org/github-workflow.json

name: main

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16.13.1]
    runs-on: ${{ matrix.os }}
    name: test on ${{ matrix.os }} and node ${{ matrix.node }}
    env:
      CI: true
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: npm install
        run: npm install
 #     - name: check lint
 #       run: npm run eslint-check
      - name: check tests
        run: npm run test
      - name: upload coverage
        - uses: actions/checkout@v2
        - uses: codecov/codecov-action@v2
          with:
            token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
            directory: ./coverage/
            path_to_write_report: ./coverage/codecov_report.txt
            files: ./coverage.xml # optional
        # run: node ./upload_coverage.mjs
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    needs: [test]
    if: success() && github.event_name == 'push'
    runs-on: ubuntu-latest
    name: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: npm install
        run: npm install
      - name: publish package
        run: node ./.github/workflows/publish_package.mjs
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: ensure github release
        run: node ./.github/workflows/github_release.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
